### PR TITLE
Add a settings view where one can disable snippets for certain packages

### PR DESCRIPTION
**Pull request by dralletje**
I know it does look kind of hacky, but this is the way it should be done I think. I am yet to dive deeper so we can reload without restarting it, maybe be just fully reloading all snippets. Made this because of this issue #55

### CODE REVIEW

**Comment by PierBover** [comment]
Hey @dralletje

I'm in the process of working in another PR for this repo and you will need to add tests (specs) to your fork.

- https://github.com/dralletje/snippets/tree/master/spec
- https://atom.io/docs/latest/hacking-atom-writing-specs

I'm not part of the atom team btw... but I'm undergoing this process which is completely new to me.

**Comment by aryzing** [comment]
Is there anything preventing the merge?

**Comment by 50Wliu** [comment]
Yes, it needs specs.

**Comment by dralletje** [comment]
Hey @50Wliu (not sure if I need to ping you), but is this enough spec that I added? 😁 
I know it is only one test, I'm not very good with tests yet

**Comment by krabbypattified** [comment]
Eagerly awaiting this feature.. any updates?

**Comment by kvsm** [comment]
Just popping in to say that it's 2017 and this default snippet malarkey is still the thing which annoys me most frequently in life. Pretty please can this be reviewed (and merged). :smile:

**Comment by lee-dohm** [comment]
The concern I have about this is that you have to restart for things to take effect. As the PR currently stands, I am 👎 on merging because of this. The system that was used to disable keybindings doesn't have this problem. Perhaps you can model this ability on that PR? https://github.com/atom/atom/pull/8130

**Comment by dralletje** [comment]
Thanks for the feedback, @lee-dohm , I share the concern.
Let me come back to this later this week with a restart-less version :-)

**Comment by lee-dohm** [comment]
Sounds good! Thanks very much for your patience and effort on this @dralletje :bow: ✨

**Comment by NanerLee** [comment]
so long time...
Eagerly awaiting this feature

**Comment by lee-dohm** [comment]
@NanerLee If you would like to see this happen, perhaps you could take a stab at improving the PR?

**Comment by layonferreira** [comment]
Hi, I have added the ability to reload snippets without the need to restart on #242

**Comment by dralletje** [comment]
@layonferreira Looks awesome! Thanks for picking up where I forgot hahaha 😁 First contribution including a test, good job :)

**Comment by dralletje** [comment]
Closing in favor of #242

**Pull request closed without merging**
